
#еще один вариант конфигурации, такой же или вместо application.properties

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/g_37_jp_shop
    username: postgres
    driver-class-name: org.postgresql.Driver
    password: postgres
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml
