
#еще один вариант конфигурации, такой же или вместо application.properties
#файл для конфигурации на удаленной машине

spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
    username: ${DB_USERNAME}
    driver-class-name: org.postgresql.Driver
    password: ${DB_PASSWORD}
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml
  jpa:
    properties:
      hibernate:
        auto_quote_keyword: true

key:
  access: aovKvB5EPC2sJF8M1vW08teR3cjH8UeqgbCLRSz1vO0=
  refresh: sEr0dbT/MOsvXxplxsitw3JOoZ8KKfoPUd0ygBcPiHQ=

messages:
  hello: Hello from Digital Ocean!