
#еще один вариант конфигурации, такой же или вместо application.properties
#файл для конфигурации на локальной машине

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/g_37_jp_shop
    username: postgres
    driver-class-name: org.postgresql.Driver
    password: postgres
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml
  jpa:
    properties:
      hibernate:
        auto_quote_keyword: true
  mail:
    username: looga.jury@gmail.com
    password: leid wdhz nczx ygbl
    host: smtp.gmail.com
    port: 587
    properties:
      mail:
        debug: true
        smtp:
          auth: true
          starttls:
            enable: true
          ssl:
            protocols: TLSv1.2
            trust: smtp.gmail.com

key:
  access: aovKvB5EPC2sJF8M1vW08teR3cjH8UeqgbCLRSz1vO0=
  refresh: sEr0dbT/MOsvXxplxsitw3JOoZ8KKfoPUd0ygBcPiHQ=

logging:
  file:
    name: logs/log.log
  level:
    root: info

messages:
  hello: Hello from local application!